services:
  php:
    container_name: job-app
    user: "${UID}:${GID}"
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - appnet

  nginx:
    image: nginx:stable
    container_name: job-nginx
    ports:
      - "8080:80"
      - "8000:8000"

    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - appnet
    labels:
      - traefik.enable=true

      # ðŸ‘‡ Ensure Traefik uses the proxy network
      - traefik.docker.network=proxy

      # Router: domain for your API
      - traefik.http.routers.job_tracker.rule=Host(`job-tracker.madush.dev`)
      - traefik.http.routers.job_tracker.entrypoints=websecure
      - traefik.http.routers.job_tracker.tls=true
      - traefik.http.routers.job_tracker.tls.certresolver=le

      # Service: nginx listens on port 80 internally
      - traefik.http.services.job_tracker.loadbalancer.server.port=80

  mysql:
    image: mysql:8.0
    container_name: job-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet
  node:
    image: node:22
    container_name: job-node-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"   # Vite dev server
    command: >
      sh -lc "npm install && npm run dev -- --host 0.0.0.0 --port 5173 || tail -f /dev/null"
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: job-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
